apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  labels:
    app: backend-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
        - name: backend-api
          image: backend_api:v1
          ports:
            - containerPort: 5006
          livenessProbe:
            httpGet:
              path: /AuthenticationService/api
              port: 5006
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /AuthenticationService/api
              port: 5006
            initialDelaySeconds: 10
            periodSeconds: 5
          env:
            - name: MONGO_URI
              value: "mongodb://root:testing@mongo:27017/?authSource=admin"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-api
spec:
  ports:
    - port: 5006
      targetPort: 5006
  selector:
    app: backend-api
  type: LoadBalancer
